import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderPage from "./header/page";
import NavbarPage from "./navbar/page";
import FooterPage from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PaperLess Document System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPage/>
       <div className="flex"> <NavbarPage/>
        {children}</div>
        <FooterPage/>
        </body>
    </html>
  );
}
